### ISSUE TITLE
LInk to Rainer Joswig’s Lisp/Newton OS article

### ISSUE THREAD

**Issue by splorp** [NewtonScript/newtonscript.github.com#18]
Mentions of NewtonScript IDE and some wonderful historical Newton tidbits.

http://lispm.de/lisp-based-newton-os

**Comment by splorp** [comment]
Closed per commit 9f6f0b2c3b3202937864d3618095b4784d3d72df

**Comment by morgant** [comment]
@splorp Thanks for adding this!
