### ISSUE TITLE
Add Filip Zawadiak’s Hammering Newton

### ISSUE THREAD

**Issue by splorp** [NewtonScript/newtonscript.github.com#24]
Discoveries, details, and other documentation uncovered while playing around with Hammer — the low level Newton debugger.

Currently residing only in the Internet Archive.

https://web.archive.org/web/20031125235030/http://newton.vyx.net/

**Comment by morgant** [comment]
I've linked to this under documentation and highlighted the Frame Store documentation as being NewtonScript-specific. Most of it is low-level C++ stuff, so maybe it'd be more appropriate under "Further Reading", but I think we can get by with it's current placement.

**Comment by splorp** [comment]
Hoo boy … this one had been ripening for a while, wasn’t it?

Thanks, Morgan.
