### ISSUE TITLE
Link to Landon Dyer's writings about the Newton & NewtonScript

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#26]
Landon Dyer has some great stories about the Newton, some of which may or may not relate to NewtonScript. See http://www.dadhacker.com/blog/?s=newtonscript & http://www.dadhacker.com/blog/?s=newton.

**Comment by splorp** [comment]
Closed per commit 93a1576

**Comment by morgant** [comment]
@splorp Thanks for adding this!

**Comment by splorp** [comment]
Just trying to muddle through the old issues.
