### ISSUE TITLE
Add link to Roger Milne's "Writing Assembly for your Newton"

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#33]
While a bit hacky and mostly regarding assembly, Roger Milne's "Writing assemby for your Newton" article does note how to call assembly from NewtonScript:

    http://web.archive.org/web/20120521121236/http://roger.trideja.com/newton/newtonasm.html

**Comment by splorp** [comment]
This is a pretty cool find.

**Comment by morgant** [comment]
Roger's site is actually alive and well at http://milne.co.nr/, incl. this documentation, so I'll be linking to that.
