### ISSUE TITLE
Link to NewtonScript slack channel

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#36]
I have set up a NewtonScript Slack channel (https://newtonscript-lang.slack.com/), which should be linked to.

**Comment by splorp** [comment]
Ooh. Sign me up. Do I need an invite?

**Comment by morgant** [comment]
@splorp The current shared invite link is https://join.slack.com/t/newtonscript-lang/shared_invite/enQtMjY5ODM0ODYzMzI4LWJkYmE0YmU1NWRjZmYxMmYwYmQ5MWE1MTQ3MzI2ODI0M2ViY2U2OGZmNWRhZDZiOGFkMmQzM2Y0N2VlYTI4ZWI, though it expires in December or something like that.

**Comment by morgant** [comment]
Note: Owners/Admins can manage the expiring invite URLs using the following link: https://newtonscript-lang.slack.com/admin/shared_invites. The links are good for 30 days (current one expires 2017-12-10).

**Comment by splorp** [comment]
I’m in.
