### ISSUE TITLE
Add Walter Smith's `prota` NewtonScript implementation

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#37]
Yesterday Walter Smith (@wrs) released [`prota`](https://github.com/wrs/prota), as close to the original NewtonScript source code as he could dig up (see [the tweet](https://twitter.com/walter_smith/status/932102752225804289)). We need to add this to the listings.

**Comment by splorp** [comment]
Closed per commit 3eeb31f9945b2e55a0de9d8d31dcfe0984d47477
