### ISSUE TITLE
Matthias Melcher has moved Einstein/BasiliskII/etc. to MessagePad.org

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#41]
Matthias Melcher has moved most (all?) of his Einstein/BasiliskII/etc. resources from elektriktrick.com to messagepad.org. So, we should add or update resources, as appropriate.

**Comment by splorp** [comment]
Is there anything at the former site that isn’t available at the latter? I would want to make sure that any legacy information is still maintained.

**Comment by morgant** [comment]
It looks like the new article link is http://messagepad.org/Newton_Script_NTK.html and includes very slightly updated content (at least, the "ramblings" section). The old article still exists, so maybe we simply update the main link and add a "Mirror:" link pointing at the original?

**Comment by morgant** [comment]
I have updated the article link to point to mesasgepad.org and added a mirror link for elektriktrick.com as mentioned above.

**Comment by morgant** [comment]
I have also submitted both links to Internet Archive's WayBack Machine. I added a mirror link to the messagepad.org page on Internet Archive.
