### ISSUE TITLE
Add ROM Soup tool

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#42]
Pablo Marx (real name?) created an macOS (nee OS X) utility for exploring the soups in a Newton MessagePad/eMate ROM:

https://github.com/pablomarx/ROM-Soup

We should link to this under tools.

**Comment by splorp** [comment]
Definitely.

Pablo Marx is the online moniker of Steve White.

https://newtonglossary.com/sources/steve-white

**Comment by morgant** [comment]
Thanks! I've added an entry.
