### ISSUE TITLE
Page build warning

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#43]
I received the following in an automated email after pushing an update today:

"The page build completed successfully, but returned the following warning for the `master` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site."

**Comment by morgant** [comment]
I have updated the A records for newtonscript.org to point to the following IP addresses, per https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain:

185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

Seems to be working.

**Comment by splorp** [comment]
I saw this error the last time I pushed an update, but everything seemed to get published ok.

Thanks for looking into it.
