### ISSUE TITLE
Add Jake Bordens' Internal Serial Enabler

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#44]
Jake Bordens developed an [Internal Serial Enabler](https://github.com/jake-b/Newton-Internal-Serial-Enabler) utility for NewtonOS, which includes the required C++ code to integrate with NewtonScript.

**Comment by morgant** [comment]
This could be added under either Libraries or Sample Code.

**Comment by splorp** [comment]
Hmmm … probably Sample Code makes the most sense, as it’s an example of working with NewtonScript, as opposed to being a library of code to integrate into something else.

Does that make sense?

**Comment by morgant** [comment]
Definitely makes sense. I've added it to the Sample Code section.
