### ISSUE TITLE
Add basic style guide to CONTRIBUTING.md

### ISSUE THREAD

**Issue by morgant** [NewtonScript/newtonscript.github.com#5]
I should add a basic style guide to CONTRIBUTING.md so that HTML, CSS, and content are more likely to be formatted consistently.

**Comment by splorp** [comment]
Here’s a little something to consider for the style guide …

Sometimes we link an entry’s title and sometimes we don’t. Personally, I’d like to always link the title to the primary source site or PDF. Also, we should include that primary source in the mirror list as well.

Thoughts?

**Comment by morgant** [comment]
My rule of thumb so far has been to only link the title to the original source. So, those sites that are no longer available only have mirror links, where something like a PDF from Apple that is still available from Apple has both the primary link & mirrors on Newted & UNNA.

**Comment by splorp** [comment]
I guess I’d like to see more consistent formatting for ease of glancing through the list.

What if we didn’t link the title in any case, but added a “primary” or “original source” link in addition to the various unofficial mirrors?

**Comment by morgant** [comment]
I like the latter suggestion of having an extra metadata line for the original source link. There are some that won't necessarily have linked titles anyway, like books & magazines, so it probably makes sense to standardize on not having linked titles.

**Comment by splorp** [comment]
Thinking about this a bit further, most of the software entries link the titles to their respective author or company sources. This makes a lot of sense. What if we link all titles to the most obvious (or only available) source — which might just be the copy from the Internet Archive or UNNA.

I’m mainly concerned with giving users a consistent place to click.

For example, the only source for both the **Newton Book Maker User’s Guide** and **Newton Formats** (and several other PDFs) is the “mirror” on UNNA. Why not just link those titles directly to the UNNA version? Forego the “mirror” section in the metadata unless there in a alternate download site available.

Likewise, we list the source for **develop** as the MacTech “mirror”. Why not just link the title to the MacTech URL?

**Comment by splorp** [comment]
I created a branch and pull request with the changes as discussed above.

Let me know what you think.

**Comment by morgant** [comment]
Thanks, I will try to check it out this week!

**Comment by morgant** [comment]
My apologies for the log delay in reviewing & merging those changes.

**Comment by splorp** [comment]
No worries. I’m just happy they passed muster.

**Comment by morgant** [comment]
Did you still want to change the headings & anchors within CONTRIBUTING.md to clean it up? anything else you feel this document could use at this time?

**Comment by splorp** [comment]
Yeppes.

I just created a pull request from the [documentation_formatting](https://github.com/NewtonScript/newtonscript.github.com/tree/documentation_formatting) branch.

**Comment by morgant** [comment]
I think this issue is resolved by your latest changed in Pull Request #31. Thanks again!

**Comment by splorp** [comment]
I love it when a plan comes together.
